version: "3"

networks:
  factory:
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  authzforce:
    image: fiware/authzforce-ce-server:release-5.4.1
    ports:
     - "8080:8080"
    networks:
     factory:
        ipv4_address: 172.18.0.5

  idm:
    image: idmprueba
    ports:
     - "5000:5000"
     - "8000:8000"
    networks:
      factory:
        ipv4_address: 172.18.0.6